# Generated by Django 5.1 on 2026-07-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('device', models.CharField(choices=[('klima', 'Klima'), ('kombi', 'Kombi'), ('beyaz_esya', 'Beyaz Eşya'), ('diger', 'Diğer')], default='klima', max_length=20, verbose_name='Cihaz')),
                ('message', models.TextField(blank=True, verbose_name='Arıza / Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Geliş Tarihi')),
                ('handled', models.BooleanField(default=False, verbose_name='İlgilenildi')),
            ],
            options={
                'verbose_name': 'Servis Talebi',
                'verbose_name_plural': 'Servis Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
